"""Platform part of the demonstration load (ISSUE-008, D6/Q15).

Reads the mocks of the prototype already converted to
``dados/plataforma.json`` (generated by ``scripts/converter_mocks.mjs``) and
writes the platform registers every module needs: the client, the three
projects of the portfolio with their weight grades, companies, people,
demonstration collaborators covering the four general profiles, the four
Weekly Scheduling roles and the three bonds, the support registers and the
initial parameters. Every date from the prototype is shifted to the run's
reference date, preserving the scenario's spacing.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

from sqlalchemy.orm import Session

from src.carga.registro import register, shift_date
from src.core import audit, recording
from src.core.models import Client
from src.modulos.configuracoes import service as config_service
from src.modulos.configuracoes.models import (
    Collaborator,
    CollaboratorScheduleRole,
    Company,
    Discipline,
    Location,
    Person,
    PortfolioWeight,
    Project,
    System,
    Unit,
)

DATA_PATH = Path(__file__).resolve().parent / "dados" / "plataforma.json"

PART_NAME = "plataforma"

# The demonstration Admin is the prototype's session user; the other people
# become collaborators so the profile selector (ISSUE-011) has every case.
ADMIN_EMAIL = "leonardo.gomes@exemplo.com"

ADMIN = "Admin"
TIMENOW = "Timenow"
FORNECEDOR = "Fornecedor"
CLIENTE = "Cliente"

# E-mail -> (perfil geral, vínculo). Every person of the mock is explicit:
# a change in the converted data fails loud instead of granting a silent default.
ACCESS: dict[str, tuple[str, str]] = {
    "leonardo.gomes@exemplo.com": (ADMIN, TIMENOW),
    "joao.gestor@exemplo.com": ("Gestor", TIMENOW),
    "maria.souza@exemplo.com": ("Membro", TIMENOW),
    "marina.alves@exemplo.com": ("Membro", TIMENOW),
    "carlos.nunes@exemplo.com": ("Membro", FORNECEDOR),
    "renata.lima@exemplo.com": ("Membro", FORNECEDOR),
    "diego.matos@exemplo.com": ("Membro", TIMENOW),
    "ana.prado@exemplo.com": ("Membro", TIMENOW),
    "paulo.serra@exemplo.com": ("Membro", TIMENOW),
    "beatriz.rocha@exemplo.com": ("Membro", TIMENOW),
    "fabio.teixeira@exemplo.com": ("Membro", FORNECEDOR),
    "rafael.costa@exemplo.com": ("Membro", TIMENOW),
    "juliana.reis@exemplo.com": ("Membro", TIMENOW),
    "paula.menezes@exemplo.com": ("Gestor", TIMENOW),
    "ricardo.tavares@exemplo.com": ("Gestor", TIMENOW),
    "sonia.ribeiro@exemplo.com": ("Membro", TIMENOW),
    "hugo.fontes@exemplo.com": ("Membro", FORNECEDOR),
    "otavio.lins@exemplo.com": ("Membro", FORNECEDOR),
}

# The prototype has no person for the Cliente bond (its session is Timenow);
# the demonstration adds one so every bond has a face (D7/Q21).
DEMO_CLIENT: dict[str, str] = {
    "nome": "Cliente Horizonte",
    "funcao": "Acompanhamento do contrato",
    "email": "visualizador@cliente.demo",
    "perfil": "Visualizador",
    "vinculo": CLIENTE,
}

# e-mail -> (projeto do mock, papel): every project has all four roles.
SCHEDULE_ROLES: tuple[tuple[str, int, str], ...] = (
    ("maria.souza@exemplo.com", 1, "Planejador"),
    ("maria.souza@exemplo.com", 3, "Planejador"),
    ("sonia.ribeiro@exemplo.com", 2, "Planejador"),
    ("rafael.costa@exemplo.com", 1, "Fiscal"),
    ("rafael.costa@exemplo.com", 2, "Fiscal"),
    ("rafael.costa@exemplo.com", 3, "Fiscal"),
    ("carlos.nunes@exemplo.com", 1, "Encarregado"),
    ("hugo.fontes@exemplo.com", 2, "Encarregado"),
    ("otavio.lins@exemplo.com", 3, "Encarregado"),
    ("fabio.teixeira@exemplo.com", 1, "Fornecedor"),
    ("renata.lima@exemplo.com", 2, "Fornecedor"),
    ("renata.lima@exemplo.com", 3, "Fornecedor"),
)


def load(session: Session, reference_date: date) -> None:
    """Write the whole platform part, inside the caller's transaction."""
    data = _read_data()
    admin = _bootstrap_admin(session, data)
    writer = Writer(session=session, author_id=admin.id, reference_date=reference_date)
    client = _load_client(writer, data)
    companies = _load_companies(writer, data)
    people = _load_people(writer, data, companies, admin)
    collaborators = _load_collaborators(writer, data, people)
    projects = _load_projects(writer, data, client, people)
    _seed_parameters(writer)
    _load_portfolio_weights(writer, data, projects)
    _load_support_registers(writer, data, projects)
    _load_schedule_roles(session, collaborators, projects)


@dataclass(frozen=True)
class Writer:
    """Sessão, autor e data de referência compartilhados pelos passos da carga."""

    session: Session
    author_id: int
    reference_date: date

    def create(self, record: Any) -> Any:
        """Grava o registro com a trilha e o controle de versão (D5b)."""
        return recording.create(self.session, user_id=self.author_id, record=record)


def _read_data() -> dict[str, Any]:
    """The converted mocks; the file is versioned and generated by the converter script."""
    return json.loads(DATA_PATH.read_text(encoding="utf-8"))


def _bootstrap_admin(session: Session, data: dict[str, Any]) -> Collaborator:
    """Create the Admin first: the trail of every other record needs an author.

    The Admin's own person and collaborator are written before any author
    exists, so they are inserted directly and get their trail lines right
    after, with the Admin himself as author.
    """
    source = _person_data(data, ADMIN_EMAIL)
    person = Person(name=source["nome"], role=source["funcao"], email=ADMIN_EMAIL)
    session.add(person)
    session.flush()
    collaborator = Collaborator(person_id=person.id, general_profile=ADMIN, bond=TIMENOW)
    session.add(collaborator)
    session.flush()
    audit.created(session, user_id=collaborator.id, entity=person.__tablename__, record=person)
    audit.created(
        session,
        user_id=collaborator.id,
        entity=collaborator.__tablename__,
        record=collaborator,
    )
    return collaborator


def _load_client(writer: Writer, data: dict[str, Any]) -> Client:
    source = data["clientes"][0]
    client = Client(name=source["nome"], acronym=source["sigla"], active=source["ativo"])
    return writer.create(client)


def _load_companies(writer: Writer, data: dict[str, Any]) -> dict[int, Company]:
    companies: dict[int, Company] = {}
    for source in data["empresas"]:
        company = Company(name=source["nome"], kind=source["tipo"])
        writer.create(company)
        companies[source["id"]] = company
    return companies


def _load_people(
    writer: Writer,
    data: dict[str, Any],
    companies: dict[int, Company],
    admin: Collaborator,
) -> dict[int, Person]:
    people: dict[int, Person] = {}
    for source in data["pessoas"]:
        if source["email"] == ADMIN_EMAIL:
            admin_person = writer.session.get(Person, admin.person_id)
            if admin_person is None:  # pragma: no cover - bootstrap wrote it
                message = "A pessoa do Admin da demonstração não foi gravada."
                raise ValueError(message)
            people[source["id"]] = admin_person
            continue
        company = companies.get(source["empresaId"])
        person = Person(
            company_id=company.id if company is not None else None,
            name=source["nome"],
            role=source["funcao"],
            email=source["email"],
        )
        writer.create(person)
        people[source["id"]] = person
    return people


def _load_collaborators(
    writer: Writer,
    data: dict[str, Any],
    people: dict[int, Person],
) -> dict[str, Collaborator]:
    collaborators: dict[str, Collaborator] = {}
    for source in data["pessoas"]:
        if source["email"] == ADMIN_EMAIL:
            continue
        person = people[source["id"]]
        profile, bond = ACCESS[source["email"]]
        collaborator = Collaborator(
            person_id=person.id,
            company_id=person.company_id if bond == FORNECEDOR else None,
            general_profile=profile,
            bond=bond,
        )
        writer.create(collaborator)
        collaborators[source["email"]] = collaborator

    client_person = Person(
        name=DEMO_CLIENT["nome"], role=DEMO_CLIENT["funcao"], email=DEMO_CLIENT["email"]
    )
    writer.create(client_person)
    client_collaborator = Collaborator(
        person_id=client_person.id,
        general_profile=DEMO_CLIENT["perfil"],
        bond=DEMO_CLIENT["vinculo"],
    )
    writer.create(client_collaborator)
    collaborators[DEMO_CLIENT["email"]] = client_collaborator
    return collaborators


def _load_projects(
    writer: Writer,
    data: dict[str, Any],
    client: Client,
    people: dict[int, Person],
) -> dict[int, Project]:
    projects: dict[int, Project] = {}
    for source in data["projetos"]:
        project = Project(
            client_id=client.id,
            manager_id=people[source["gerenteId"]].id,
            code=source["codigo"],
            name=source["nome"],
            pep=source["pep"],
            ata_pattern=source["padraoAta"],
            risk_pattern=source["padraoRisco"],
            punch_pattern=source["padraoPunch"],
            risk_appetite=source["apetiteRisco"],
            start_date=shift_date(date.fromisoformat(source["inicio"]), writer.reference_date),
            expected_end_date=shift_date(
                date.fromisoformat(source["terminoPrevisto"]), writer.reference_date
            ),
            budget_cents=source["orcamentoCentavos"],
        )
        writer.create(project)
        projects[source["id"]] = project
    return projects


def _seed_parameters(writer: Writer) -> None:
    """Version 1 of every parameter group, effective on the run's reference date."""
    config_service.seed_initial_parameters(
        writer.session,
        author_id=writer.author_id,
        effective_from=writer.reference_date,
    )


def _load_portfolio_weights(
    writer: Writer,
    data: dict[str, Any],
    projects: dict[int, Project],
) -> None:
    """The weight grades of ``projetos[].ponderacao`` inside the portfolio version."""
    version = config_service.current_version(
        writer.session, group="portfolio", reference_date=writer.reference_date
    )
    if version is None:
        return
    for source in data["projetos"]:
        project = projects[source["id"]]
        for criterion, grade in source["ponderacao"].items():
            writer.session.add(
                PortfolioWeight(
                    version_id=version.id,
                    project_id=project.id,
                    criterion=criterion,
                    grade=grade,
                )
            )


def _load_support_registers(
    writer: Writer,
    data: dict[str, Any],
    projects: dict[int, Project],
) -> None:
    for source in data["sistemas"]:
        system = System(
            project_id=projects[source["projetoId"]].id,
            code=source["codigo"],
            name=source["nome"],
            area=source.get("area"),
        )
        writer.create(system)
    for source in data["locais"]:
        location = Location(
            project_id=projects[source["projetoId"]].id,
            code=source["codigo"],
            name=source["nome"],
        )
        writer.create(location)
    for name in data["disciplinas"]:
        writer.create(Discipline(name=name))
    for source in data["unidades"]:
        unit = Unit(kind=source["tipo"], code=source["codigo"], name=source["nome"])
        writer.create(unit)


def _load_schedule_roles(
    session: Session,
    collaborators: dict[str, Collaborator],
    projects: dict[int, Project],
) -> None:
    for email, project_id, role in SCHEDULE_ROLES:
        session.add(
            CollaboratorScheduleRole(
                collaborator_id=collaborators[email].id,
                project_id=projects[project_id].id,
                role=role,
            )
        )


def _person_data(data: dict[str, Any], email: str) -> dict[str, Any]:
    for source in data["pessoas"]:
        if source["email"] == email:
            return source
    message = f"A pessoa {email} não está nos dados convertidos da plataforma."
    raise ValueError(message)


register(PART_NAME, load)
