"""plataforma

Revision ID: 0001
Revises:
Create Date: 2026-10-05 14:58:42.855950

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogo",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("grupo", sa.Text(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalogo")),
        sa.UniqueConstraint("grupo", "nome", name=op.f("uq_catalogo_grupo_nome")),
    )
    op.create_table(
        "cliente",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("sigla", sa.Text(), nullable=True),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cliente")),
    )
    op.create_table(
        "disciplina",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disciplina")),
        sa.UniqueConstraint("nome", name=op.f("uq_disciplina_nome")),
    )
    op.create_table(
        "empresa",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=True),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_empresa")),
    )
    op.create_table(
        "unidade",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unidade")),
        sa.UniqueConstraint("tipo", "codigo", name=op.f("uq_unidade_tipo_codigo")),
    )
    op.create_table(
        "catalogo_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("catalogo_id", sa.BigInteger(), nullable=False),
        sa.Column("chave", sa.Text(), nullable=False),
        sa.Column("valor", sa.Text(), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalogo_id"], ["catalogo.id"], name=op.f("fk_catalogo_item_catalogo_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalogo_item")),
        sa.UniqueConstraint(
            "catalogo_id", "chave", name=op.f("uq_catalogo_item_catalogo_id_chave")
        ),
    )
    op.create_table(
        "pessoa",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("empresa_id", sa.BigInteger(), nullable=True),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("funcao", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresa.id"], name=op.f("fk_pessoa_empresa_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pessoa")),
        sa.UniqueConstraint("email", name=op.f("uq_pessoa_email")),
    )
    op.create_table(
        "colaborador",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("pessoa_id", sa.BigInteger(), nullable=False),
        sa.Column("empresa_id", sa.BigInteger(), nullable=True),
        sa.Column("perfil_geral", sa.Text(), nullable=False),
        sa.Column("vinculo", sa.Text(), nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["empresa_id"], ["empresa.id"], name=op.f("fk_colaborador_empresa_id")
        ),
        sa.ForeignKeyConstraint(
            ["pessoa_id"], ["pessoa.id"], name=op.f("fk_colaborador_pessoa_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_colaborador")),
        sa.UniqueConstraint("pessoa_id", name=op.f("uq_colaborador_pessoa_id")),
    )
    op.create_table(
        "projeto",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=False),
        sa.Column("gerente_id", sa.BigInteger(), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("pep", sa.Text(), nullable=True),
        sa.Column("padrao_ata", sa.Text(), nullable=True),
        sa.Column("padrao_risco", sa.Text(), nullable=True),
        sa.Column("padrao_punch", sa.Text(), nullable=True),
        sa.Column("apetite_risco", sa.Text(), nullable=True),
        sa.Column("inicio", sa.Date(), nullable=True),
        sa.Column("termino_previsto", sa.Date(), nullable=True),
        sa.Column("orcamento_centavos", sa.BigInteger(), nullable=True),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(["cliente_id"], ["cliente.id"], name=op.f("fk_projeto_cliente_id")),
        sa.ForeignKeyConstraint(["gerente_id"], ["pessoa.id"], name=op.f("fk_projeto_gerente_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projeto")),
        sa.UniqueConstraint("codigo", name=op.f("uq_projeto_codigo")),
    )
    op.create_table(
        "anexo",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=False),
        sa.Column("enviado_por_id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("tipo_mime", sa.Text(), nullable=False),
        sa.Column("tamanho_bytes", sa.BigInteger(), nullable=False),
        sa.Column("hash", sa.Text(), nullable=False),
        sa.Column("origem_tabela", sa.Text(), nullable=False),
        sa.Column("origem_registro_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "enviado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enviado_por_id"], ["colaborador.id"], name=op.f("fk_anexo_enviado_por_id")
        ),
        sa.ForeignKeyConstraint(["projeto_id"], ["projeto.id"], name=op.f("fk_anexo_projeto_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anexo")),
    )
    op.create_table(
        "auditoria",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=True),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("data_hora", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entidade", sa.Text(), nullable=False),
        sa.Column("registro_id", sa.BigInteger(), nullable=False),
        sa.Column("acao", sa.Text(), nullable=False),
        sa.Column("antes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("depois", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["projeto_id"], ["projeto.id"], name=op.f("fk_auditoria_projeto_id")
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"], ["colaborador.id"], name=op.f("fk_auditoria_usuario_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auditoria")),
    )
    op.create_table(
        "colaborador_papel_programacao",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("colaborador_id", sa.BigInteger(), nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=False),
        sa.Column("papel", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["colaborador_id"],
            ["colaborador.id"],
            name=op.f("fk_colaborador_papel_programacao_colaborador_id"),
        ),
        sa.ForeignKeyConstraint(
            ["projeto_id"], ["projeto.id"], name=op.f("fk_colaborador_papel_programacao_projeto_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_colaborador_papel_programacao")),
        sa.UniqueConstraint(
            "colaborador_id",
            "projeto_id",
            "papel",
            name=op.f("uq_colaborador_papel_programacao_colaborador_id_projeto_id_papel"),
        ),
    )
    op.create_table(
        "local",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(["projeto_id"], ["projeto.id"], name=op.f("fk_local_projeto_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_local")),
        sa.UniqueConstraint("projeto_id", "codigo", name=op.f("uq_local_projeto_id_codigo")),
    )
    op.create_table(
        "notificacao",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=False),
        sa.Column("originado_por_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("canal", sa.Text(), nullable=False),
        sa.Column("destinatarios", sa.Text(), nullable=False),
        sa.Column("assunto", sa.Text(), nullable=False),
        sa.Column("corpo", sa.Text(), nullable=False),
        sa.Column("situacao", sa.Text(), nullable=False),
        sa.Column("referencia_entidade", sa.Text(), nullable=True),
        sa.Column("referencia_registro_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["originado_por_id"], ["colaborador.id"], name=op.f("fk_notificacao_originado_por_id")
        ),
        sa.ForeignKeyConstraint(
            ["projeto_id"], ["projeto.id"], name=op.f("fk_notificacao_projeto_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notificacao")),
    )
    op.create_table(
        "parametro_versao",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("autor_id", sa.BigInteger(), nullable=False),
        sa.Column("grupo", sa.Text(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.Column("vigencia_inicio", sa.Date(), nullable=False),
        sa.Column("justificativa", sa.Text(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["autor_id"], ["colaborador.id"], name=op.f("fk_parametro_versao_autor_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parametro_versao")),
        sa.UniqueConstraint("grupo", "versao", name=op.f("uq_parametro_versao_grupo_versao")),
    )
    op.create_table(
        "sequencia_numeracao",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("proximo_valor", sa.BigInteger(), nullable=False),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["projeto_id"], ["projeto.id"], name=op.f("fk_sequencia_numeracao_projeto_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sequencia_numeracao")),
        sa.UniqueConstraint(
            "projeto_id", "tipo", name=op.f("uq_sequencia_numeracao_projeto_id_tipo")
        ),
    )
    op.create_table(
        "sistema",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=False),
        sa.Column("codigo", sa.Text(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("area", sa.Text(), nullable=True),
        sa.Column("versao", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(["projeto_id"], ["projeto.id"], name=op.f("fk_sistema_projeto_id")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sistema")),
        sa.UniqueConstraint("projeto_id", "codigo", name=op.f("uq_sistema_projeto_id_codigo")),
    )
    op.create_table(
        "parametro_valor",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("versao_id", sa.BigInteger(), nullable=False),
        sa.Column("chave", sa.Text(), nullable=False),
        sa.Column("ordem", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.Text(), nullable=False),
        sa.Column("valor", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["versao_id"], ["parametro_versao.id"], name=op.f("fk_parametro_valor_versao_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parametro_valor")),
        sa.UniqueConstraint(
            "versao_id", "chave", "ordem", name=op.f("uq_parametro_valor_versao_id_chave_ordem")
        ),
    )
    op.create_table(
        "portfolio_ponderacao",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("versao_id", sa.BigInteger(), nullable=False),
        sa.Column("projeto_id", sa.BigInteger(), nullable=False),
        sa.Column("criterio", sa.Text(), nullable=False),
        sa.Column("nota", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["projeto_id"], ["projeto.id"], name=op.f("fk_portfolio_ponderacao_projeto_id")
        ),
        sa.ForeignKeyConstraint(
            ["versao_id"], ["parametro_versao.id"], name=op.f("fk_portfolio_ponderacao_versao_id")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_ponderacao")),
        sa.UniqueConstraint(
            "versao_id",
            "projeto_id",
            "criterio",
            name=op.f("uq_portfolio_ponderacao_versao_id_projeto_id_criterio"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("portfolio_ponderacao")
    op.drop_table("parametro_valor")
    op.drop_table("sistema")
    op.drop_table("sequencia_numeracao")
    op.drop_table("parametro_versao")
    op.drop_table("notificacao")
    op.drop_table("local")
    op.drop_table("colaborador_papel_programacao")
    op.drop_table("auditoria")
    op.drop_table("anexo")
    op.drop_table("projeto")
    op.drop_table("colaborador")
    op.drop_table("pessoa")
    op.drop_table("catalogo_item")
    op.drop_table("unidade")
    op.drop_table("empresa")
    op.drop_table("disciplina")
    op.drop_table("cliente")
    op.drop_table("catalogo")
    # ### end Alembic commands ###
